### ISSUE TITLE
Emphasis regression?

### ISSUE THREAD

**Issue by puzrin** [jgm/commonmark.js#12] opened 2015-03-05 18:09 UTC
http://spec.commonmark.org/dingus/?text=_%28hai%29_.%20%3C-%20bad%0A%0A_%28hai%29_%0A%0A*%28hai%29*.%0A%0A

Happened somewhere after 0.15.

Is it a bug or intentional behaviour, when user should use `*`?

**Comment by bevacqua** [comment] 2015-03-05 18:24
I'll copy my comment here for reference. Here are the conditions to reproduce:

- Use `_` or `__`
  - Finish the underscored text with `)`, followed by 1+ white space characters `_)    ` _(in this case, no closing `.` is necessary)_
  - Add a `.` right after the closing underscores, `_)     `.` _(in this case, you can have any amount of whitespace before the closing underscore)

Failing to convert:

- `_) _`
- `__) __`
- `_)_.`
- `__)__.`
- `_)      _.`

Succeeding:

- `_)_`
- `__)__`

In my opinion `*` and `_` should behave identically at all times (both single and doubles). It's really strange that these corner cases behave one way using underscores and another using asterisks. Particularly when the rules for the parsing bug seem so arbitrary

**Comment by jgm** [comment] 2015-03-05 18:33
This behavior can be explained in terms of this rule:

> A single `_` character can close emphasis iff it is part of a right-flanking delimiter run and not part of a left-flanking delimiter run.

When you have `_(hai)_` by itself, the second `_` is right- but not  left-flanking.

However, when you have `_(hai)_.`, the second `_` is now both left- and right-flanking.

We could perhaps make the rule a bit more complicated (though I liked its simplicity).

> A single `_` character can close emphasis iff it is part of a right-flanking delimiter run and either (a) not part of a left-flanking delimiter run or (b) part of a left-flanking delimiter run followed by punctuation.

**Comment by bevacqua** [comment] 2015-03-05 18:55
How does the `*` rule look like? Shouldn't `_` match whatever `*` is doing?

**Comment by puzrin** [comment] 2015-03-05 19:00
@bevacqua http://spec.commonmark.org/0.18/#emphasis-and-strong-emphasis

**Comment by bevacqua** [comment] 2015-03-05 19:19
Thanks @puzrin. I'll maintain my suggestion then, I propose we make `_` behave just like `*` does in this case.

**Comment by jgm** [comment] 2015-03-05 19:29
The reason they behave differently is to disallow `_` from creating emphasis when it occurs inside words, like_this_one.

**Comment by bevacqua** [comment] 2015-03-05 19:33
But it should still be able to emphasize punctuation-delimited text _(like this one)_

**Comment by puzrin** [comment] 2015-03-11 13:08
> We could perhaps make the rule a bit more complicated (though I liked its simplicity).
>> A single _ character can close emphasis iff it is part of a right-flanking delimiter run and either (a) not part of a left-flanking delimiter run or (b) part of a left-flanking delimiter run followed by punctuation.

I like it. We updated `markdown-it` to use this logic in v4.+ (next). Hope to see it in spec. Personally, i'm not touched by this regression, but it looks unpleasant.

**Comment by jgm** [comment] 2015-04-12 14:43
I just ran into this issue with something like:

    __`Bar.Baz`__.

which I expected to be strong emphasis.  I haven't had time lately to work on the spec, but this makes me even more favorably inclined towards @puzrin's sugestion above.

**Closed** 2015-04-28 06:00 UTC
